dataset : "kraken_2035_wfd"
dataroot: "/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperSims/v1/kraken_2035/RBTEST_WFD_1aCC_Y10_G10_kraken_2035/"
prefix_Ia: "RBTEST_WFD_1aCC_Y10_G10_Ia-"
prefix_NONIa: "RBTEST_WFD_1aCC_Y10_G10_NONIa-"
training_set:
    - 0.05
    - 0.03
    - 0.01
    - 0.009
    - 0.007
    - 0.005
    - 0.003
    - 0.001
classifiers:
    - 'random_forest'
