rocs:
    - file: '/home/tallam/snmachine/examples/output_data/output_colossus_2664_ddf_Y1_no_z/classifications_9123/waveletsrandom_forest2000.roc'
      auc: '/home/tallam/snmachine/examples/output_data/output_colossus_2664_ddf_Y1_no_z/classifications_9123/waveletsrandom_forest2000.auc'
      norm_types: '/home/tallam/snmachine/examples/output_data/output_colossus_2664_ddf_Y1_no_z/colossus_2664_ddf_Y1_types_normalised.csv'
      probs: '/home/tallam/snmachine/examples/output_data/output_colossus_2664_ddf_Y1_no_z/classifications_9123/waveletsrandom_forest2000.probs'
    - file: '/home/tallam/snmachine/examples/output_data/output_colossus_2665_ddf_Y1_no_z/classifications_9124/waveletsrandom_forest2000.roc'
      auc: '/home/tallam/snmachine/examples/output_data/output_colossus_2665_ddf_Y1_no_z/classifications_9124/waveletsrandom_forest2000.auc'
      norm_types: '/home/tallam/snmachine/examples/output_data/output_colossus_2665_ddf_Y1_no_z/colossus_2665_ddf_Y1_types_normalised.csv'
      probs: '/home/tallam/snmachine/examples/output_data/output_colossus_2665_ddf_Y1_no_z/classifications_9124/waveletsrandom_forest2000.probs'
