rocs:
    - file: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest1.roc'
      ratio: 0.001
      types: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/kraken_2026_wfd_types.csv'
      sim: 'kraken_2026_wfd'
      auc: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest1.auc'
    - file: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest3.roc'
      ratio: 0.003
      types: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/kraken_2026_wfd_types.csv'
      sim: 'kraken_2026_wfd'
      auc: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest3.auc'
    - file: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest5.roc'
      ratio: 0.005
      types: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/kraken_2026_wfd_types.csv'
      sim: 'kraken_2026_wfd'
      auc: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest5.auc'
    - file: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest7.roc'
      ratio: 0.007
      types: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/kraken_2026_wfd_types.csv'
      sim: 'kraken_2026_wfd'
      auc: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest7.auc'
    - file: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest9.roc'
      ratio: 0.009
      types: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/kraken_2026_wfd_types.csv'
      sim: 'kraken_2026_wfd'
      auc: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest9.auc'
    - file: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest10.roc'
      ratio: 0.01
      types: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/kraken_2026_wfd_types.csv'
      sim: 'kraken_2026_wfd'
      auc: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest10.auc'
    - file: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest30.roc'
      ratio: 0.03
      types: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/kraken_2026_wfd_types.csv'
      sim: 'kraken_2026_wfd'
      auc: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest30.auc'
    - file: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest50.roc'
      ratio: 0.05
      types: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/kraken_2026_wfd_types.csv'
      sim: 'kraken_2026_wfd'
      auc: '/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperClassResults/output_data/output_kraken_2026_wfd_no_z/classifications_8967/waveletsrandom_forest50.auc'
