rocs:
    - file: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest1.roc'
      ratio: 0.001
      types: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/kraken_2026_ddf_types.csv'
      sim: 'kraken_2026_ddf'
      auc: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest1.auc'
    - file: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest3.roc'
      ratio: 0.003
      types: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/kraken_2026_ddf_types.csv'
      sim: 'kraken_2026_ddf'
      auc: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest3.auc'
    - file: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest5.roc'
      ratio: 0.005
      types: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/kraken_2026_ddf_types.csv'
      sim: 'kraken_2026_ddf'
      auc: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest5.auc'
    - file: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest7.roc'
      ratio: 0.007
      types: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/kraken_2026_ddf_types.csv'
      sim: 'kraken_2026_ddf'
      auc: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest7.auc'
    - file: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest9.roc'
      ratio: 0.009
      types: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/kraken_2026_ddf_types.csv'
      sim: 'kraken_2026_ddf'
      auc: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest9.auc'
    - file: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest10.roc'
      ratio: 0.01
      types: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/kraken_2026_ddf_types.csv'
      sim: 'kraken_2026_ddf'
      auc: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest10.auc'
    - file: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest30.roc'
      ratio: 0.03
      types: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/kraken_2026_ddf_types.csv'
      sim: 'kraken_2026_ddf'
      auc: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest30.auc'
    - file: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest50.roc'
      ratio: 0.05
      types: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/kraken_2026_ddf_types.csv'
      sim: 'kraken_2026_ddf'
      auc: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8964/waveletsrandom_forest50.auc'
