rocs:
    - file: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8931/waveletsrandom_forest2.roc'
      auc: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/classifications_8931/waveletsrandom_forest2.auc'
      ratio: 0.02
      types: '/home/tallam/snmachine/examples/output_data/output_kraken_2026_ddf_no_z/kraken_2026_ddf_types.csv'
      sim: 'kraken_2026_ddf'
    - file: '/home/tallam/snmachine/examples/output_data/output_kraken_2035_ddf_no_z/classifications_8971/waveletsrandom_forest10.roc'
      auc: '/home/tallam/snmachine/examples/output_data/output_kraken_2035_ddf_no_z/classifications_8971/waveletsrandom_forest10.auc'
      ratio: 0.01
      types: '/home/tallam/snmachine/examples/output_data/output_kraken_2035_ddf_no_z/kraken_2035_ddf_types.csv'
      sim: 'kraken_2035_ddf'
