# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: snmachine

channels:
  - conda-forge

dependencies:
  - astropy>=1.1.2
  - jupyter>=1.0.0
  - matplotlib>=1.5.1
  - numpy>=1.18.4
  - scikit-learn=0.20.0
  - scipy>=0.17.0
  - george>=0.3.0
  - iminuit==1.2
  - pandas>=0.23.0
  - extinction>=0.3.0
  - imbalanced-learn>=0.4.3
  - python=3.7
  - pip>=20.1

  - pip:
    - emcee>=2.1.0
    - numpydoc>=0.6.0
    - pytest-remotedata>=0.3.1
    - pywavelets>=0.4.0
    - sncosmo==2.1.0
    - nose>=1.3.7
    - future>=0.16
    - pyyaml>=3.13
    - pytest-xdist>=1.26.1
    - seaborn
    - schwimmbad
    - cesium
    - tqdm
    - lightgbm
