# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: snmachine

dependencies:
  - astropy>=1.1.2
  - jupyter>=1.0.0
  - matplotlib=1.5.1
  - numpy=1.11.0
  - scikit-learn=0.18.1
  - scipy>=0.17.0

  - pip:
    - emcee>=2.1.0
    - iminuit>=1.2
    - numpydoc>=0.6.0
    - pywavelets>=0.4.0
    - sncosmo>=1.3.0
    - nose>=1.3.7
    - george>=0.3.0
    - future>=0.16
    - sphinx_rtd_theme>=0.2.4

