dataset : "kraken_2035_ddf"
dataroot: "/share/hypatia/snmachine_resources/data/LSST_Cadence_WhitePaperSims/v1/kraken_2035/RBTEST_DDF_IaCC_Y10_G10_kraken_2035/"
prefix_Ia: "RBTEST_DDF_MIXED_Y10_G10_Ia-"
prefix_NONIa: "RBTEST_DDF_MIXED_Y10_G10_NONIa-"
training_set:
    - 0.05
    - 0.04
    - 0.03
    - 0.02
    - 0.01
classifiers:
    - 'random_forest'
