dataset : "kraken_2044_wfd_Y10"
dataroot: "/share/hypatia/snmachine_resources/data/cwp/WFDY10/RH_kraken_2044_wfd_WFD_1aONLY_Y10_G10/"
prefix_Ia: "RH_WFD_1aONLY_Y10_G10_Ia-"
prefix_NONIa: "RH_WFD_1aONLY_Y10_G10_NONIa-"
classifiers:
    - 'random_forest'
